/**
 * Per-category profile files for migrated gold-standard members (Phase 17b architecture).
 * One JSON per destination view under lib/data/generated/profiles/{bioguideId}/.
 * Other members continue to read from the topicPositions mega-bundle.
 *
 * Profile JSON imports are generated by scripts/generate-profile-index.ts → profiles/index.ts
 */
import {
  MIGRATED_PROFILE_BIOGUIDE_LIST,
  PROFILE_CONTROVERSIES as PROFILE_CONTROVERSIES_RAW,
  PROFILE_ENDORSEMENTS as PROFILE_ENDORSEMENTS_RAW,
  PROFILE_FINANCE as PROFILE_FINANCE_RAW,
  PROFILE_NEWS as PROFILE_NEWS_RAW,
  PROFILE_TRADES as PROFILE_TRADES_RAW,
  PROFILE_ORG_VOTE_LINKS_RAW,
  PROFILE_POSITIONS,
  PROFILE_SAID_DID,
  PROFILE_STATEMENTS,
  PROFILE_VOTES as PROFILE_VOTES_RAW,
} from './generated/profiles/index';
import type { OrgVoteTopicLink } from './buildOrgVoteTopicLinks';
import type { FecFinanceEntry } from './fecFinance';
import type { Controversy, NewsItem, Source, StockTrade, VoteRecord } from '../types';
import type {
  PlatformPositionEntry,
  SaidDidLinkEntry,
  TopicPositionData,
  TopicStatementEntry,
} from './topicPositions';
import { leadSummary } from './displaySummary';
import { getNationalNewsArticles, nationalArticlesToNewsItems } from './newsNational';
import { getPoliticianByBioguide } from './allPoliticians';
import { applyNewsCorroboration, tokensFromMemberNames } from './newsCorroboration';
import { normalizeUrlForDedupe } from './sourceIntegrity';
import currentLegislators from './generated/currentLegislators.json';

interface NewsLegislatorNameRecord {
  bioguideId: string;
  name?: string;
  firstName?: string;
  lastName?: string;
}

const currentLegislatorNamesByBioguide = new Map<string, NewsLegislatorNameRecord>(
  ((currentLegislators as { legislators?: NewsLegislatorNameRecord[] }).legislators ?? [])
    .filter((leg) => !!leg.bioguideId)
    .map((leg) => [leg.bioguideId, leg]),
);

function pushName(parts: string[], value?: string): void {
  const trimmed = value?.trim();
  if (trimmed) parts.push(trimmed);
}

function pushFullName(parts: string[], firstName?: string, lastName?: string): void {
  const first = firstName?.trim();
  const last = lastName?.trim();
  if (first && last) parts.push(`${first} ${last}`);
}

/**
 * Name tokens to exclude from news corroboration overlap for a bioguide.
 * Include both display roster names and legal legislator names so SSR does not
 * re-verify profile news with a narrower token set than the sync pipeline used.
 */
export function memberProfileNewsNameTokensForBioguide(bioguideId: string): Set<string> {
  const parts: string[] = [];
  const p = getPoliticianByBioguide(bioguideId);
  if (p) {
    pushName(parts, p.name);
    pushName(parts, p.firstName);
    pushName(parts, p.lastName);
    pushFullName(parts, p.firstName, p.lastName);
  }
  const leg = currentLegislatorNamesByBioguide.get(bioguideId);
  if (leg) {
    pushName(parts, leg.name);
    pushName(parts, leg.firstName);
    pushName(parts, leg.lastName);
    pushFullName(parts, leg.firstName, leg.lastName);
  }
  return tokensFromMemberNames(parts);
}

function isDisplayableStatement(statement: TopicStatementEntry): boolean {
  if (statement.tier === 'media' || statement.tier === 'alleged') {
    return statement.verbatim === true;
  }
  return true;
}

/** Members migrated off the topicPositions mega-bundle (from profiles/_manifest.json). */
export const MIGRATED_PROFILE_BIOGUIDES = new Set<string>(MIGRATED_PROFILE_BIOGUIDE_LIST);

export function usesMemberProfile(bioguideId: string): boolean {
  return MIGRATED_PROFILE_BIOGUIDES.has(bioguideId);
}

interface StatementsFile {
  byTopic: Record<string, { statements: TopicStatementEntry[] }>;
}

interface PositionsFile {
  byTopic: Record<string, { platformPositions: PlatformPositionEntry[] }>;
}

interface SaidDidFile {
  byTopic: Record<string, SaidDidLinkEntry[]>;
}

interface ProfileVotesFile {
  bioguideId: string;
  politicianId: string;
  chamber?: 'house' | 'senate';
  votes: VoteRecord[];
  asOf: string;
  status?: 'unavailable';
  source?: Source;
  note?: string;
}

interface ProfileFinanceFile {
  bioguideId: string;
  entry: FecFinanceEntry | null;
}

/** Roll-call votes materialized from data/national/votes/congress-votes.json. */
export interface MemberProfileCongressVotes {
  politicianId: string;
  bioguideId: string;
  chamber: 'house' | 'senate';
  votes: VoteRecord[];
  source: Source;
  asOf: string;
}

const PROFILE_DATA: Record<
  string,
  { statements: StatementsFile; positions: PositionsFile; saidDid: SaidDidFile }
> = Object.fromEntries(
  MIGRATED_PROFILE_BIOGUIDE_LIST.map((id) => [
    id,
    {
      statements: PROFILE_STATEMENTS[id as keyof typeof PROFILE_STATEMENTS] as StatementsFile,
      positions: PROFILE_POSITIONS[id as keyof typeof PROFILE_POSITIONS] as PositionsFile,
      saidDid: PROFILE_SAID_DID[id as keyof typeof PROFILE_SAID_DID] as SaidDidFile,
    },
  ]),
);

const ORG_VOTE_LINKS: Record<string, OrgVoteTopicLink[]> = Object.fromEntries(
  MIGRATED_PROFILE_BIOGUIDE_LIST.map((id) => [
    id,
    ((PROFILE_ORG_VOTE_LINKS_RAW[id as keyof typeof PROFILE_ORG_VOTE_LINKS_RAW] as { links: OrgVoteTopicLink[] })
      ?.links ?? []),
  ]),
);

const PROFILE_VOTES: Record<string, ProfileVotesFile> = PROFILE_VOTES_RAW as Record<
  string,
  ProfileVotesFile
>;

const PROFILE_FINANCE: Record<string, ProfileFinanceFile> = PROFILE_FINANCE_RAW as Record<
  string,
  ProfileFinanceFile
>;

const PROFILE_NEWS: Record<string, ProfileNewsFile> = PROFILE_NEWS_RAW as Record<
  string,
  ProfileNewsFile
>;

interface ProfileTradesFile {
  bioguideId: string;
  status: 'filled' | 'honest-gap' | 'fetch-failed';
  note?: string;
  trades: StockTrade[];
}

const PROFILE_TRADES: Record<string, ProfileTradesFile> = PROFILE_TRADES_RAW as Record<
  string,
  ProfileTradesFile
>;

interface ProfileControversiesFile {
  bioguideId: string;
  items: Controversy[];
}

interface EndorsementEntry {
  name: string;
  office: string;
  politicianId?: string;
  date?: string;
  source?: Source;
}

interface ProfileEndorsementsFile {
  bioguideId: string;
  endorses: EndorsementEntry[];
  endorsedBy: EndorsementEntry[];
}

const PROFILE_CONTROVERSIES: Record<string, ProfileControversiesFile> =
  PROFILE_CONTROVERSIES_RAW as Record<string, ProfileControversiesFile>;

const PROFILE_ENDORSEMENTS: Record<string, ProfileEndorsementsFile> =
  PROFILE_ENDORSEMENTS_RAW as Record<string, ProfileEndorsementsFile>;

/**
 * Reconstruct TopicPositionData map from per-category profile files.
 * Returns null when the member has not been migrated.
 */
export function getMemberProfileTopicPositions(
  bioguideId: string,
): Record<string, TopicPositionData> | null {
  const bundle = PROFILE_DATA[bioguideId];
  if (!bundle) return null;

  const topicIds = new Set<string>([
    ...Object.keys(bundle.statements.byTopic ?? {}),
    ...Object.keys(bundle.positions.byTopic ?? {}),
    ...Object.keys(bundle.saidDid.byTopic ?? {}),
  ]);

  const out: Record<string, TopicPositionData> = {};

  for (const topicId of topicIds) {
    const statements = (bundle.statements.byTopic[topicId]?.statements ?? []).filter(
      isDisplayableStatement,
    );
    const platformPositions = bundle.positions.byTopic[topicId]?.platformPositions ?? [];
    const saidDidLinks = bundle.saidDid.byTopic[topicId] ?? [];

    if (
      statements.length === 0 &&
      platformPositions.length === 0 &&
      saidDidLinks.length === 0
    ) {
      continue;
    }

    out[topicId] = {
      statements,
      saidDidLinks,
      ...(platformPositions.length > 0 ? { platformPositions } : {}),
    };
  }

  return Object.keys(out).length > 0 ? out : null;
}

export function getMemberProfileOrgVoteLinks(bioguideId: string): OrgVoteTopicLink[] | null {
  if (!MIGRATED_PROFILE_BIOGUIDES.has(bioguideId)) return null;
  return ORG_VOTE_LINKS[bioguideId] ?? [];
}

/**
 * Roll-call votes for migrated profiles — materialized from data/national/votes/congress-votes.json.
 */
export function getMemberProfileVotes(bioguideId: string): MemberProfileCongressVotes | null {
  const file = PROFILE_VOTES[bioguideId];
  if (!file || file.status === 'unavailable' || file.votes.length === 0) return null;
  return {
    politicianId: file.politicianId,
    bioguideId: file.bioguideId,
    chamber: file.chamber ?? inferChamberFromVotes(file.votes),
    votes: file.votes,
    source: file.source ?? {
      name: 'Congress.gov',
      url: 'https://www.congress.gov',
      tier: 'official',
    },
    asOf: file.asOf,
  };
}

function inferChamberFromVotes(votes: VoteRecord[]): 'house' | 'senate' {
  const id = votes[0]?.id ?? '';
  if (/\-h119\-/i.test(id) || /-\d{6}-119-\d+-/i.test(id)) return 'house';
  return 'senate';
}

/** FEC totals for migrated profiles — materialized from data/national/fec/congress-finance.json. */
export function getMemberProfileFinance(bioguideId: string): FecFinanceEntry | null {
  if (!MIGRATED_PROFILE_BIOGUIDES.has(bioguideId)) return null;
  return PROFILE_FINANCE[bioguideId]?.entry ?? null;
}

interface ProfileNewsFile {
  bioguideId: string;
  items: NewsItem[];
  status?: 'filled' | 'honest-gap' | 'fetch-failed' | 'fetch-blocked';
  note?: string;
}

/**
 * News items for migrated profiles — materialized from
 * generated/profiles/{bioguideId}/news.json (Group C: approved-outlet journalism only).
 * Rendered headline/summary text is display-only here; the underlying `headline` and
 * `summary` fields on disk are never mutated (source-integrity guards check the raw fields).
 * Returns null (never `[]` as a false "verified empty") when the fetch is blocked and no
 * prior verified items exist, so callers can fall back rather than show an honest-gap that
 * isn't actually verified absence.
 */
export function getMemberProfileNews(bioguideId: string): NewsItem[] | null {
  const file = PROFILE_NEWS[bioguideId];
  if (!file) return null;
  if (
    file.items.length === 0 &&
    (file.status === 'fetch-failed' || file.status === 'fetch-blocked')
  ) {
    return null;
  }
  return file.items.map((item) => ({
    ...item,
    summary: leadSummary(item.summary || item.headline, 200) || item.headline,
  }));
}

/**
 * STOCK Act gap metadata for migrated profiles — from profiles/{bioguideId}/trades.json.
 * Returns null when no profile file or trades are present on disk.
 */
export function getMemberProfileTradeGap(
  bioguideId: string,
): { status: 'honest-gap' | 'fetch-failed'; note: string } | null {
  if (!MIGRATED_PROFILE_BIOGUIDES.has(bioguideId)) return null;
  const file = PROFILE_TRADES[bioguideId];
  if (!file || file.trades.length > 0) return null;
  if (file.status !== 'honest-gap' && file.status !== 'fetch-failed') return null;
  const note = file.note?.trim();
  if (!note) return null;
  return { status: file.status, note };
}

/**
 * Display news for a politician page: prefer the migrated profile's news.json
 * (Group C RSS pipeline, approved outlets only); supplement from newsNational.json
 * (GDELT) when the profile file has fewer than the display target.
 */
export function mergeProfileNews(legacyNews: NewsItem[] | undefined, bioguideId?: string): NewsItem[] {
  if (bioguideId && MIGRATED_PROFILE_BIOGUIDES.has(bioguideId)) {
    const profileNews = getMemberProfileNews(bioguideId) ?? [];
    const seen = new Set(profileNews.map((i) => normalizeUrlForDedupe(i.url ?? i.source.url ?? '')));
    const merged = [...profileNews];
    if (merged.length < 15) {
      const national = nationalArticlesToNewsItems(bioguideId, getNationalNewsArticles(bioguideId));
      for (const item of national) {
        const key = normalizeUrlForDedupe(item.url ?? item.source.url ?? '');
        if (seen.has(key)) continue;
        seen.add(key);
        merged.push(item);
      }
    }
    merged.sort((a, b) => b.date.localeCompare(a.date));
    if (merged.length > 0) {
      return applyNewsCorroboration(
        merged,
        memberProfileNewsNameTokensForBioguide(bioguideId),
      ).slice(0, 15);
    }
  }
  return legacyNews ?? [];
}

/**
 * Controversies for migrated profiles — prefer profile file over mock.
 * Returns null when no profile data exists (caller should fall back to mock).
 */
export function getMemberProfileControversies(bioguideId: string): Controversy[] | null {
  if (!MIGRATED_PROFILE_BIOGUIDES.has(bioguideId)) return null;
  const file = PROFILE_CONTROVERSIES[bioguideId];
  if (!file || file.items.length === 0) return null;
  return file.items;
}

/**
 * Endorsements for migrated profiles — prefer profile file over mock.
 * Returns null when no profile data exists (caller should fall back to mock).
 */
export function getMemberProfileEndorsements(bioguideId: string): ProfileEndorsementsFile | null {
  if (!MIGRATED_PROFILE_BIOGUIDES.has(bioguideId)) return null;
  const file = PROFILE_ENDORSEMENTS[bioguideId];
  if (!file) return null;
  if (file.endorses.length === 0 && file.endorsedBy.length === 0) return null;
  return file;
}

/**
 * Merge controversies: for migrated members prefer profile files;
 * otherwise return empty (honest gap — mock data is quarantined).
 */
export function mergeProfileControversies(legacyControversies: Controversy[] | undefined, bioguideId?: string): Controversy[] {
  if (bioguideId && MIGRATED_PROFILE_BIOGUIDES.has(bioguideId)) {
    const profileData = getMemberProfileControversies(bioguideId);
    if (profileData && profileData.length > 0) return profileData;
  }
  return legacyControversies ?? [];
}

/**
 * Merge endorsements: for migrated members prefer profile files;
 * otherwise return undefined (honest gap — mock data is quarantined).
 */
export function mergeProfileEndorsements(
  legacyEndorsements: { endorses: EndorsementEntry[]; endorsedBy: EndorsementEntry[] } | undefined,
  bioguideId?: string,
): { endorses: EndorsementEntry[]; endorsedBy: EndorsementEntry[] } | undefined {
  if (bioguideId && MIGRATED_PROFILE_BIOGUIDES.has(bioguideId)) {
    const profileData = getMemberProfileEndorsements(bioguideId);
    if (profileData) return { endorses: profileData.endorses, endorsedBy: profileData.endorsedBy };
  }
  return legacyEndorsements;
}
