/**
 * Generate profiles/_manifest.json and profiles/index.ts from disk.
 * Output: lib/data/generated/profiles/_manifest.json, profiles/index.ts
 * Run: npm run generate:profile-index
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadProfileDisplayIdentityByBioguide } from './lib/profileDisplayIdentity';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const profilesRoot = path.join(projectRoot, 'lib', 'data', 'generated', 'profiles');

const CATEGORY_FILES = [
  'statements',
  'positions',
  'saidDid',
  'orgVoteLinks',
  'votes',
  'finance',
  'news',
  'controversies',
  'endorsements',
] as const;

async function main(): Promise<void> {
  const entries = await readdir(profilesRoot, { withFileTypes: true });
  const bioguides = entries
    .filter((e) => e.isDirectory() && /^[A-Z]\d{6}$/.test(e.name))
    .map((e) => e.name)
    .sort();

  const identityByBioguide = loadProfileDisplayIdentityByBioguide(projectRoot);

  const manifestMembers: Array<{
    bioguideId: string;
    name: string;
    initials: string;
    categories: string[];
    politicianId?: string;
  }> = [];

  for (const bioguideId of bioguides) {
    const dir = path.join(profilesRoot, bioguideId);
    const files = await readdir(dir);
    const categories = CATEGORY_FILES.filter((c) => files.includes(`${c}.json`));
    let politicianId: string | undefined;
    if (files.includes('manifest.json')) {
      try {
        const m = JSON.parse(await readFile(path.join(dir, 'manifest.json'), 'utf8')) as {
          politicianId?: string;
        };
        politicianId = m.politicianId;
      } catch {
        /* ignore */
      }
    }
    const identity = identityByBioguide.get(bioguideId);
    if (!identity?.name || !identity.initials) {
      throw new Error(
        `Missing display identity for ${bioguideId} — join roster.json or currentLegislators.json by bioguideId`,
      );
    }
    manifestMembers.push({
      bioguideId,
      name: identity.name,
      initials: identity.initials,
      categories,
      politicianId,
    });
  }

  const masterManifest = {
    generatedAt: new Date().toISOString(),
    count: bioguides.length,
    members: manifestMembers,
  };

  await writeFile(
    path.join(profilesRoot, '_manifest.json'),
    `${JSON.stringify(masterManifest, null, 2)}\n`,
    'utf8',
  );

  const importLines: string[] = [];
  const mapBlocks: Record<string, string[]> = {
    PROFILE_STATEMENTS: [],
    PROFILE_POSITIONS: [],
    PROFILE_SAID_DID: [],
    PROFILE_ORG_VOTE_LINKS: [],
    PROFILE_VOTES: [],
    PROFILE_FINANCE: [],
    PROFILE_NEWS: [],
    PROFILE_CONTROVERSIES: [],
    PROFILE_ENDORSEMENTS: [],
  };

  for (const id of bioguides) {
    for (const cat of CATEGORY_FILES) {
      const member = manifestMembers.find((m) => m.bioguideId === id);
      if (!member?.categories.includes(cat)) continue;
      const varName = `${id}_${cat}`;
      importLines.push(`import ${varName} from './${id}/${cat}.json';`);
      const mapKey =
        cat === 'statements'
          ? 'PROFILE_STATEMENTS'
          : cat === 'positions'
            ? 'PROFILE_POSITIONS'
            : cat === 'saidDid'
              ? 'PROFILE_SAID_DID'
              : cat === 'orgVoteLinks'
                ? 'PROFILE_ORG_VOTE_LINKS'
                : cat === 'votes'
                  ? 'PROFILE_VOTES'
                  : cat === 'finance'
                    ? 'PROFILE_FINANCE'
                    : cat === 'news'
                      ? 'PROFILE_NEWS'
                      : cat === 'controversies'
                        ? 'PROFILE_CONTROVERSIES'
                        : 'PROFILE_ENDORSEMENTS';
      mapBlocks[mapKey].push(`  ${id}: ${varName},`);
    }
  }

  const indexTs = `/** AUTO-GENERATED by scripts/generate-profile-index.ts — do not edit manually */
${importLines.join('\n')}

export const MIGRATED_PROFILE_BIOGUIDE_LIST = ${JSON.stringify(bioguides)} as const;
export type MigratedBioguideId = (typeof MIGRATED_PROFILE_BIOGUIDE_LIST)[number];

export const PROFILE_STATEMENTS = {
${mapBlocks.PROFILE_STATEMENTS.join('\n')}
} as const;

export const PROFILE_POSITIONS = {
${mapBlocks.PROFILE_POSITIONS.join('\n')}
} as const;

export const PROFILE_SAID_DID = {
${mapBlocks.PROFILE_SAID_DID.join('\n')}
} as const;

export const PROFILE_ORG_VOTE_LINKS_RAW = {
${mapBlocks.PROFILE_ORG_VOTE_LINKS.join('\n')}
} as const;

export const PROFILE_VOTES = {
${mapBlocks.PROFILE_VOTES.join('\n')}
} as const;

export const PROFILE_FINANCE = {
${mapBlocks.PROFILE_FINANCE.join('\n')}
} as const;

export const PROFILE_NEWS = {
${mapBlocks.PROFILE_NEWS.join('\n')}
} as const;

export const PROFILE_CONTROVERSIES = {
${mapBlocks.PROFILE_CONTROVERSIES.join('\n')}
} as const;

export const PROFILE_ENDORSEMENTS = {
${mapBlocks.PROFILE_ENDORSEMENTS.join('\n')}
} as const;
`;

  await writeFile(path.join(profilesRoot, 'index.ts'), indexTs, 'utf8');
  console.log(`Generated manifest (${bioguides.length} members) and profiles/index.ts`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
